apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-ms
  template:
    metadata:
      labels:
        app: mongo-ms
    spec:
      containers:
        - name: container
          image: mongo:3.6
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-ms
spec:
  type: ClusterIP
  selector:
    app: mongo-ms
  ports:
    - port: 27017
      targetPort: 27017
