export enum QUEUE_NAME {
  ORCHESTATOR_EVENT = "ORCHESTATOR_EVENT",
  ORDER_CREATE_EVENT = "ORDER_CREATE_EVENT",
  BILLED_ORDER_EVENT = "BILLED_ORDER_EVENT",
}

export enum TYPE_MESSAGE {
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_BILLED = "ORDER_BILLED",
}

export enum EXCHANGE_NAME {
  FAILED_ERROR_EXCHANGE = "FAILED_ERROR_EXCHANGE",
  ORDER_CONFIRMED_EXCHANGE = "ORDER_CONFIRMED_EXCHANGE",
}

export enum EXCHANGE_TYPE {
  TOPIC = "topic",
  FANOUT = "fanout",
}

export enum ROUTING_KEY_ERROR {
  STORE_ERROR = "store.order_cancelled.error",
  DELIVERY_ERROR = "delivery.order_cancelled.error",
}
