apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  storageClassName: gp2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-prd
  template:
    metadata:
      labels:
        app: mysql-prd
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: pvc-mysql
