version: "3.8"

services:
  mongo-orders-ms:
    image: mongo:bionic
    container_name: mongo-ms-orders
    ports:
      - "27017:27017"
    volumes:
      - mongo-persist:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net-ms

  orders-ms:
    build:
      context: .
      dockerfile: orders-ms/Dockerfile
    image: img-orders-ms
    container_name: orders-ms
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=12345
      - MONGO_HOST=mongo-orders-ms
      - MONGO_PORT=27017
      - MONGO_DATABASE=order
      - MONGO_AUTH_SOURCE=admin
      - RABBITMQ_HOST=rabbitmq
    networks:
      - net-ms
    depends_on:
      - mongo-orders-ms
    restart: always

volumes:
  mongo-persist:

networks:
  net-ms:
