export enum QUEUE_NAME {
  ORCHESTATOR_EVENT = "ORCHESTATOR_EVENT",
  ORDER_DELIVERIED_EVENT = "ORDER_DELIVERIED_EVENT",
}

export enum TYPE_MESSAGE {
  ORDER_CREATED = "ORDER_CREATED",
}

export enum EXCHANGE_NAME {
  FAILED_ERROR_EXCHANGE = "FAILED_ERROR_EXCHANGE",
  ORDER_CONFIRMED_EXCHANGE = "ORDER_CONFIRMED_EXCHANGE",
}

export enum EXCHANGE_TYPE {
  TOPIC = "topic",
  FANOUT = "fanout",
}

export enum ROUTING_KEY_ERROR {
  ORDER_CANCELLED = "*.order_cancelled.error",
}
